name: casino
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  go_router: ^14.2.0
  get_it: ^7.7.0
  flutter_bloc: ^8.1.6
  flutter_native_splash: ^2.4.1
  easy_localization: ^3.0.7
  equatable: ^2.0.5
  flutter_screenutil: ^5.9.3
  logger: ^2.3.0
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
  assets:
    - lib/core/resources/icons/svg/
    - lib/core/resources/translations/
    - lib/core/resources/splash/

  fonts:
    - family: SFProRounded
      fonts:
        - asset: lib/core/resources/fonts/SF-Pro-Rounded-Black.otf
        - asset: lib/core/resources/fonts/SF-Pro-Rounded-Bold.otf
        - asset: lib/core/resources/fonts/SF-Pro-Rounded-ExtraBold.otf
        - asset: lib/core/resources/fonts/SF-Pro-Rounded-Light.otf
        - asset: lib/core/resources/fonts/SF-Pro-Rounded-Medium.otf
        - asset: lib/core/resources/fonts/SF-Pro-Rounded-Regular.otf
        - asset: lib/core/resources/fonts/SF-Pro-Rounded-SemiBold.otf
        - asset: lib/core/resources/fonts/SF-Pro-Rounded-Thin.otf
        - asset: lib/core/resources/fonts/SF-Pro-Rounded-ExtraLight.otf